language: python

# Only 3.4 is supported due to use of Enum
python:
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests ; python applications.py
